name: API to readme
on:
  schedule:
    - cron: "11 11 * * *"

jobs:
  update_routes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: doc
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node-version }}"
      - run: npm install
      - run: rm package-lock.json
      - run: npm run docs
      - uses: gr2m/create-or-update-pull-request-action@v1.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: "API"
          branch: "readme-api"
          commit-message: "docs(README): sync API"
